// This file is automatically generated by Genkit. Do not edit manually.
'use server';
/**
 * @fileOverview A password strength analyzer AI agent.
 *
 * - analyzePasswordStrength - A function that handles the password strength analysis process.
 * - AnalyzePasswordStrengthInput - The input type for the analyzePasswordStrength function.
 * - AnalyzePasswordStrengthOutput - The return type for the analyzePasswordStrength function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzePasswordStrengthInputSchema = z.object({
  password: z.string().describe('The password to analyze.'),
});
export type AnalyzePasswordStrengthInput = z.infer<typeof AnalyzePasswordStrengthInputSchema>;

const AnalyzePasswordStrengthOutputSchema = z.object({
  strength: z
    .string()
    .describe(
      'The strength of the password. Can be one of: very weak, weak, moderate, strong, very strong.'
    ),
  reason: z.string().describe('The reason for the password strength rating.'),
  suggestions: z.array(z.string()).describe('Suggestions for improving the password strength.'),
});
export type AnalyzePasswordStrengthOutput = z.infer<typeof AnalyzePasswordStrengthOutputSchema>;

export async function analyzePasswordStrength(
  input: AnalyzePasswordStrengthInput
): Promise<AnalyzePasswordStrengthOutput> {
  return analyzePasswordStrengthFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzePasswordStrengthPrompt',
  input: {schema: AnalyzePasswordStrengthInputSchema},
  output: {schema: AnalyzePasswordStrengthOutputSchema},
  prompt: `You are a password security expert. You will analyze the strength of the given password and provide a strength rating, a reason for the rating, and suggestions for improvement.

Password: {{{password}}}

Respond in JSON format.

Consider these password security requirements:
- Minimum length of 8 characters
- Use of uppercase and lowercase letters
- Use of numbers
- Use of special characters
- Avoidance of common words and patterns

Strength ratings:
- very weak: Extremely easy to crack.
- weak: Easy to crack.
- moderate: Relatively difficult to crack.
- strong: Difficult to crack.
- very strong: Extremely difficult to crack.

Suggestions:
- Increase the length of the password.
- Use a mix of uppercase and lowercase letters.
- Use numbers and special characters.
- Avoid common words and patterns.
`,
});

const analyzePasswordStrengthFlow = ai.defineFlow(
  {
    name: 'analyzePasswordStrengthFlow',
    inputSchema: AnalyzePasswordStrengthInputSchema,
    outputSchema: AnalyzePasswordStrengthOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
