services:
  - type: web
    name: retailpass
    runtime: node
    env: node
    region: oregon
    plan: free
    branch: master
    buildCommand: rm -rf .next node_modules/.cache && npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
